### ISSUE TITLE
a question about container startup

### ISSUE THREAD

**Issue by liudaoziwa** [Moe-hacker/asl#1]
script file named "Ruri_service.sh" it should be put in modules path and renamed "service.sh", As the module startup script, instead of putting it in service.d folder it doesn't      work then my phone restart. the way I mention is working in my phone. it should be considered to adapt more phone and it may be the standard of magisk modules ?

**Comment by Moe-hacker** [comment]
https://github.com/Moe-hacker/asl/commit/cf07c8a82a08100634645d2540c109874738679f
I hope I've fixed this.
Thanks for reporting.

**Comment by lin1328** [comment]
Perhaps you should check the documentation. In this case, it is acceptable because once the script is stored in the module path, it won't run when the module is disabled
This is not exclusive to Magisk; Kernel/Apatch also provides the same functionality.
https://github.com/topjohnwu/Magisk/blob/master/docs/guides.md

**Comment by liudaoziwa** [comment]
> Perhaps you should check the documentation. In this case, it is acceptable because once the script is stored in the module path, it won't run when the module is disabled This is not exclusive to Magisk; Kernel/Apatch also provides the same functionality. https://github.com/topjohnwu/Magisk/blob/master/docs/guides.md

the script seems to be not automatically running when my device restart ,If the script is stored in the service.d .I move the script into modules path and restart my device ,the container is automatically running

**Comment by lin1328** [comment]
> > Perhaps you should check the documentation. In this case, it is acceptable because once the script is stored in the module path, it won't run when the module is disabled This is not exclusive to Magisk; Kernel/Apatch also provides the same functionality. https://github.com/topjohnwu/Magisk/blob/master/docs/guides.md
> 
> the script seems to be not automatically running when my device restart ,If the script is stored in the service.d .I move the script into modules path and restart my device ,the container is automatically running 

Actually, I’ve also struggled with this issue. Initially, the script was placed in the module directory. However, if the module gets disabled for any reason, you can only manually execute the script or re-enable the module and restart the device, which is inconvenient. For your specific case, I haven’t encountered it before, but I’ve used different root management tools on various devices without any issues, so I placed it in a common directory. If you think it must be run from the module directory to work properly, you can fork the repository to modify the code or copy the installed files to the module directory after installation.

**Comment by lin1328** [comment]
Actually, I’ve also struggled with this issue. Initially, the script was placed in the module directory. However, if the module gets disabled for any reason, you can only manually execute the script or re-enable the module and restart the device, which is inconvenient. For your specific case, I haven’t encountered it before, but I’ve used different root management tools on various devices without any issues, so I placed it in a common directory. If you think it must be run from the module directory to work properly, you can fork the repository to modify the code or copy the installed files to the module directory after installation.
